### ISSUE TITLE
Add permission android.permission.INSTALL_PACKAGES

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-api#122]
This requires for pm install <apk_file>

**Comment by sdrausty** [comment]
@Auxilus Thanks for opening this issue here.  It does seem like a better place since termux-api is where we give Termux Android permissions.  It seems that `pm` would like more than just android.permission.INSTALL_PACKAGES permission.  
```
$ pm install --user 0 downloads/builtAPKs/step2201712271514430572.apk
        pkg: downloads/builtAPKs/step2201712271514430572.apk
Error: java.lang.SecurityException: Neither user 10094 nor current process has android.permission.INSTALL_PACKAGES.
```

How far away are we from making `pm` work on device for a nonroot Termux user?  This will be way cool with https://sdrausty.github.io/buildAPKs/ as it will provide a direct install feature for APKs built on device in Termux!

**Comment by Auxilus** [comment]
@sdrausty I don't think we need rooted device for `pm install`

**Comment by sdrausty** [comment]
@Auxilus neither do I.  It appears that the easiest way to break Android (and Termux) is to root and simply wait.  After a while the entire system is messed up, which is not surprising since rooting breaks all the system safeguards.  

Their seem to be many different permissions `pm` wants depending on how it is invoked.  What do you think about the `pm user` option?  Can we have multiple apps using Android group permissions to exchange data?  For example a file manager like https://github.com/sdrausty/buildAPKsBrowsers/tree/master/ghostcommander-code that can access Termux user space and Android space on device?

**Comment by AbdullahM0hamed** [comment]
Should be solved  by 6eaff65ced929ec247f979fae907d00a2325cfb2

**Comment by xeffyr** [comment]
@AbdullahM0hamed Not solved because it can't. `pm` copies APK into /data/local/tmp, at least on my device, which isn't possible without root. Another issue is that non-interactive installation of APKs is allowed only for Google Play and ADB. Rest of apps should start installation through GUI Android package manager.

I'm closing this.
