### ISSUE TITLE
termux-dialog doesn't exit when back key is pressed. 

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#78]
When a termux-dialog box is open and you either press the back key or tap on the darked out area, it closes the dialog box but the process doesn't exit. It should probably be treated the same way as cancel (related #77). I want to use the dialog box from termux-notification actions, which leads to stuck background tasks.

**Comment by fornwall** [comment]
Fixed in v0.14, which is rolling out to the Play Store as we speak and should be available on F-Droid within a day.

**Comment by Neo-Oli** [comment]
Thanks, but the problem still exists when tapping in the gray space. 
![tmp_6151-screen1862468759](https://cloud.githubusercontent.com/assets/7983745/24807263/d69997be-1bb7-11e7-8dd9-feac85bae893.gif)

**Comment by fornwall** [comment]
@Neo-Oli Hm, playing around with this makes we wonder if we should prevent the dialog from being closed when pressed outside?

It's a bit easy to do that by mistake, so perhaps it's best to only cancel the dialog on either the 
Cancel button or the Back key? What do you think?

**Comment by Neo-Oli** [comment]
I'd be fine with that. Just as long it doesn't cause a stuck background process in my workflow ;)

**Comment by fornwall** [comment]
Thanks! This should now be fixed in v0.15 of the Termux:API app which has now been released (and should be available as an update shortly).
